In [1]:
import pandas as pd

df1 = pd.read_excel("./매각_.xlsx")
df1.head()

,Unnamed: 0,기본,주소,상세주소,A,카맵,land,나라,주변역,입금가(만원),...,고객,핸드폰,이메일,회사전화,자택전화,방향,메모,기타메모,건물특징,기타특징
0,0,카페밤비,서울 마포구 망원동 57-498,NaN,A,카카오,랜드북,나라,망원역(6호선),"195,000",...,이재남 691015-2,NaN,NaN,NaN,NaN,빌딩온 이경민 차장 010-2181-1840,"서울특별시 마포구 양화로 45, 101동 406호 (서교동,메세나폴리스)",2018.02.13 리모델링,◈ 본 건물은 망원역(6호선)에서 도보 3분거리에 위치한 역세권 건물로 접근성이 우...,NaN
1,1,삼우빌딩,서울 강남구 개포동 1228,NaN,A,카카오,랜드북,나라,양재시민의숲역(신분당선),"1,200,000",...,차동주 580926-1 박숙향 610315-2,박숙향 010-7270-9416,NaN,NaN,NaN,전속 : 010-8940-4979,전소유주 이보희 490311-2\n\n이보희 010-3398-4431,**월세 2002 -> 2200으로 변동/ 상세는 조금씩 올렸으니 알아서~,◆ 본 건물은 양재시민의숲역(신분당선) 인근 대로변 삼면 코너에 위치한 건물로 접근...,NaN
2,2,룩홈게스트하우스,서울 중구 남산동2가 27-12,-21,A,카카오,랜드북,나라,명동역(4호선),"500,000",...,"박주연8903302,박세희900912-2,",아버지 : 010-9609-0317,NaN,NaN,NaN,NaN,필동로5길20\n\n경기도 양평군 양서면 왯재길53,NaN,▶ 본 건물은 명동역(4호선)으로부터 도보 약 4분 거리에 위치해 접근성이 우수합니...,NaN
3,3,무신사스탠다드,서울 중구 남대문로2가 5-3,199-15,A,카카오,랜드북,나라,NaN,0,...,디디아이명동엔위탁관리부동산투자회사,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,4,수환빌딩,서울 강남구 논현동 33-15,NaN,A,카카오,랜드북,나라,학동역(7호선),"1,600,000",...,손민홍 700117,사무실풍경중개법인 전속 김경환본부장 010-9124-8756,NaN,02-517-8393,NaN,전속 : 사무실풍경중개법인 김지연실장 010-6835-1200,"서울시 서초구 잠원로 117,102동 2404호 (잠원동,아크로리버뷰신반포)\n20...",광고금지,▶ 본 건물은 학동역(7호선)으로부터 411m 도보6분 거리에 위치한 역세권 이면사...,NaN

In [2]:
df2 = pd.read_excel("./보류.xlsx")
df2.head()

,Unnamed: 0,기본,주소,상세주소,A,카맵,land,나라,주변역,입금가(만원),...,고객,핸드폰,이메일,회사전화,자택전화,방향,메모,기타메모,건물특징,기타특징
0,0,송연빌딩,서울 송파구 송파동 89-2,NaN,A,카카오,랜드북,나라,"석촌역(8호선, 9호선)","1,500,000",...,김용진 600719-1,김용진 010-7397-1497,NaN,NaN,NaN,NaN,"서울특별시 송파구 잠실로 88, 131동 401호(잠실동, 레이크팰리스)",*2009.7 소유권이전,"◈ 석촌역(8호선, 9호선) 도보 1분거리 초역세권 대로변에 위치한 건물로 대중교통...",NaN
1,1,서경빌딩,서울 성북구 보문동2가 137-1,NaN,A,카카오,랜드북,나라,"보문역(6호선, 우이신설선)","400,000",...,이인완 690819-2,이인완 010-9919-3650,NaN,NaN,NaN,NaN,경기도 하남시 감초로184번길 54-32(초이동),"보문동2가 137-1, 보문동2가 144-1 동일 소유주 / 두 필지 같이 매각 원...","★ 보문역(6호선 , 우이신설선) 바로 앞에 초역세권 대로변에 위치한 건물로 대중교...",NaN
2,2,초원빌,서울 성북구 석관동 180-8,NaN,A,카카오,랜드북,나라,"석계역 (1호선, 6호선)","185,000",...,임지현 660909-2,임지현 010-5698-8949,NaN,NaN,여동생 010-2311-9322,NaN,"양천구 목동서로400,1011동 202호\n신정동(목동,신시가지아파트)\n\n밸16.9",개봉동 198-19 가평부지 같은 소유자\n*다중주택\n*원룸갯수 : 16개,"◈ 석계역(1호선, 6호선) 5번출구에서 418 m(도보 6분)\n◈ 대지면적 51...",NaN
3,3,서문빌딩,서울 마포구 서교동 368-22,NaN,A,카카오,랜드북,나라,"합정역 (2호선, 6호선)","3,300,000",...,주식회사동희 130111-0,사모 010-5471-9622,"대표이사 강만희, 강동준","과장 홍병희 010-9363-3539, 02-517-0673",과장 홍병희 02-516-2858,부장 송정용 010-8881-9069,경기도 시흥시 경기과기대로 252(정왕동)\n\n대표이사 \n강만희 480116-1...,(주)동희 02-6261-3782,"◆ 본 건물은 합정역(2호선, 6호선) 도보 5분 역세권 거리에 위치해 있어 대중교...",NaN
4,4,장고키친,서울 성동구 성수동1가 668-140,NaN,A,카카오,랜드북,나라,뚝섬역(2호선) 서울숲역(분당선),"700,000",...,강원애 481108-2 김지연 740812-2,김지연: 010-8866-5760,NaN,NaN,NaN,NaN,"서울특별시 서초구 동광로27길 88, 701호(반포동, 끄레메빌)\n\n밸83.3억...",* 2017.6 34.9억 매매 \n지구단위계획구역(뚝섬주변지역)\n*실거래 : 성...,본 건물은 뚝섬역(2호선) 도보4분 거리에 위치한 건물로 접근성이 우수함. 성수동 ...,NaN

In [3]:
df3 = pd.read_excel("./완료1_.xlsx")
df3.head()

,Unnamed: 0,기본,주소,상세주소,A,카맵,land,나라,주변역,입금가(만원),...,고객,핸드폰,이메일,회사전화,자택전화,방향,메모,기타메모,건물특징,기타특징
0,0,상암바라라,서울 마포구 상암동 1452,NaN,A,카카오,랜드북,나라,"디지털미디어시티역(6호선, 공항선, 경의중앙선)","450,000",...,김진성 701025-1 유연아 780311-2,유연아 010-8714-2448,NaN,NaN,NaN,NaN,"경기도 고양시 일산동구 일산로 206, 302동 102호 (마두동,백마마을)",NaN,"◈ 디지털미디어시티역(6호선, 경의중앙선, 공항선)에서 도보 2분 거리 초역세권 위...",NaN
1,1,공릉역신축부지16,서울 노원구 공릉동 441-24,NaN,A,카카오,랜드북,나라,공릉역(7호선),"130,000",...,"최광철 711223-1, 최성례 800107-2",최광철 010-3724-9440,NaN,NaN,NaN,NaN,"서울특별시 노원구 공릉로34길 86, 110동1304호(공릉동,태릉해링턴플레이스)",NaN,▶ 공릉역(7호선) 도보 약 5분 거리에 위치한 건물로 대중교통 접근성 뛰어남.\n...,NaN
2,2,녹사평역신축부지32,서울 용산구 이태원동 225-207,90,A,카카오,랜드북,나라,녹사평역(6호선),"290,000",...,황민숙 470307-2,사위 전준형 010-9615-2804,NaN,NaN,NaN,NaN,서울 용산구 이태원동 260-60,황민숙님 돌아가심\n\n이태원동 225-207 76\n이태원동 225 - 90 30,◆ 녹사평역(6호선)도보 7분 거리 역세권에 위치한 건물로 대중교통 접근성이 뛰어남...,NaN
3,3,희원빌딩,서울 종로구 경운동 1-9,8,A,카카오,랜드북,나라,안국역(3호선),"490,000",...,윤인숙 680315-2,윤인숙 010-3736-9481,NaN,윤인숙 직통 02-6338-9481,NaN,NaN,서울특별시 종로구 삼일대로32길 22-4 (경운동),NaN,★ 안국역(3호선) 도보 3분 거리 초역세권에 위치한 건물로 대중교통 접근성이 뛰어...,NaN
4,4,대도빌딩,서울 중구 주자동 44-2,NaN,A,카카오,랜드북,나라,"충무로역(3호선, 4호선)","650,000",...,김정수 370215-2,김정수 010-3741-2237,NaN,"010-5228-4142, 02-2267-8609",NaN,NaN,성동구 구의동 233-21,NaN,"▶ 충무로역(3호선, 4호선) 도보 3분 거리 대로변 코너에 위치한 건물로 대중교통...",NaN

In [4]:
df4 = pd.read_excel("./준비_.xlsx")
df4.head()

,Unnamed: 0,기본,주소,상세주소,A,카맵,land,나라,주변역,입금가(만원),...,고객,핸드폰,이메일,회사전화,자택전화,방향,메모,기타메모,건물특징,기타특징
0,0,NaN,서울 은평구 신사동 19-153,NaN,A,카카오,랜드북,나라,NaN,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,그랜드필드,서울 중구 남산동1가 16-6,NaN,A,카카오,랜드북,나라,NaN,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2,라루체웨딩홀,서울 중구 남산동1가 13-6,NaN,A,카카오,랜드북,나라,NaN,0,...,주식회사투데이아트,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,3,123호스텔,서울 중구 남산동2가 36-6,NaN,A,카카오,랜드북,나라,NaN,0,...,성광제620622-1,NaN,NaN,NaN,NaN,NaN,성광제 : 강남구 신사동 청록빌라,NaN,NaN,NaN
4,4,오요명동5롯지,서울 중구 남산동2가 33-3,NaN,A,카카오,랜드북,나라,NaN,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
select_feature = [
    '기본', '주소', '상세주소', 'A', '카맵', 'land', '나라', '주변역',
       '입금가(만원)', '기타매매가(만원)', '매매가(만원)', '수익률', '보증금(만원)', '평단가(만원)',
       '월 임대료(만원)', '관리비지출(만원)', '관리비(만원)', '관리비기타(만원)', '대출현황', '지목', '용도지역',
       '토지면적평', '토지면적미터', '미터당 공시지가(원)', '평당 공시지가(만원)', '공시합계(만원)', '도로',
       '사용승인일', '냉난방', '연면적평', '연면적미터', '지하층', '지상층', '승강기', '건폐율', '용적률',
       '주차방식', '주차대수', '고객', '핸드폰', '이메일', '회사전화', '자택전화', '방향', '메모', '기타메모',
       '건물특징', '기타특징'
]

In [17]:
df1["지목"].unique()

array(['대', '사옥용', '-지목-', 'EV 0 대', '수익용', '2종일반주거지역', '공장용지',
       '3종일반주거지역', '리모델링용', '주유소용지', '신축부지용도', '주차장', '준공업지역', '1종일반주거지역',
       'EV 3 대', '일반상업지역', '준주거지역', '병원', '-용도지역-', 'EV 1 대', '잡종지',
       '목장용지', '1종전용주거지역', '임야', '도로', '공원', '노선상업지역', '전', '종교용지',
       '근린상업지역', '자연녹지지역', '중심상업지역', '보전녹지지역', '일반공업지역', '답'],
      dtype=object)

In [15]:
df1["지목"].value_counts()

지목
대           7378
-지목-        5346
EV 0 대      2374
수익용          305
신축부지용도       161
2종일반주거지역     111
사옥용           59
리모델링용         59
3종일반주거지역      44
일반상업지역        43
-용도지역-        20
1종일반주거지역      19
준주거지역         16
자연녹지지역        15
주유소용지         12
준공업지역         12
공장용지          12
병원            10
주차장            9
잡종지            7
보전녹지지역         6
근린상업지역         6
1종전용주거지역       6
중심상업지역         5
노선상업지역         4
종교용지           3
EV 1 대         2
일반공업지역         2
전              2
임야             2
EV 3 대         1
공원             1
도로             1
목장용지           1
답              1
Name: count, dtype: int64

In [ ]:
df1["승강기"].value_counts()

승강기
EV 0 대     10361
-승강기-       2378
EV 1 대      2147
개별냉난방        375
-냉난방-        208
EV 2 대       171
자주식          152
-주차방식-       140
EV 3 대        37
EV 5 대        29
EV 4 대        23
자주식+기계식       19
중앙냉난방         11
기계식            3
-              1
Name: count, dtype: int64

In [9]:
df2["지목"].unique()

array(['대', '수익용', '사옥용', '신축부지용도', '-지목-', '리모델링용', '공장용지', '주유소용지', '전',
       '답', '병원', '종교용지', '임야', '잡종지', 'EV 0 대', '주차장', '도로', '철도용지'],
      dtype=object)

In [ ]:
df2[select_feature].head()

,기본,주소,상세주소,A,카맵,land,나라,주변역,입금가(만원),기타매매가(만원),...,고객,핸드폰,이메일,회사전화,자택전화,방향,메모,기타메모,건물특징,기타특징
0,송연빌딩,서울 송파구 송파동 89-2,NaN,A,카카오,랜드북,나라,"석촌역(8호선, 9호선)","1,500,000",NaN,...,김용진 600719-1,김용진 010-7397-1497,NaN,NaN,NaN,NaN,"서울특별시 송파구 잠실로 88, 131동 401호(잠실동, 레이크팰리스)",*2009.7 소유권이전,"◈ 석촌역(8호선, 9호선) 도보 1분거리 초역세권 대로변에 위치한 건물로 대중교통...",NaN
1,서경빌딩,서울 성북구 보문동2가 137-1,NaN,A,카카오,랜드북,나라,"보문역(6호선, 우이신설선)","400,000",NaN,...,이인완 690819-2,이인완 010-9919-3650,NaN,NaN,NaN,NaN,경기도 하남시 감초로184번길 54-32(초이동),"보문동2가 137-1, 보문동2가 144-1 동일 소유주 / 두 필지 같이 매각 원...","★ 보문역(6호선 , 우이신설선) 바로 앞에 초역세권 대로변에 위치한 건물로 대중교...",NaN
2,초원빌,서울 성북구 석관동 180-8,NaN,A,카카오,랜드북,나라,"석계역 (1호선, 6호선)","185,000",NaN,...,임지현 660909-2,임지현 010-5698-8949,NaN,NaN,여동생 010-2311-9322,NaN,"양천구 목동서로400,1011동 202호\n신정동(목동,신시가지아파트)\n\n밸16.9",개봉동 198-19 가평부지 같은 소유자\n*다중주택\n*원룸갯수 : 16개,"◈ 석계역(1호선, 6호선) 5번출구에서 418 m(도보 6분)\n◈ 대지면적 51...",NaN
3,서문빌딩,서울 마포구 서교동 368-22,NaN,A,카카오,랜드북,나라,"합정역 (2호선, 6호선)","3,300,000",NaN,...,주식회사동희 130111-0,사모 010-5471-9622,"대표이사 강만희, 강동준","과장 홍병희 010-9363-3539, 02-517-0673",과장 홍병희 02-516-2858,부장 송정용 010-8881-9069,경기도 시흥시 경기과기대로 252(정왕동)\n\n대표이사 \n강만희 480116-1...,(주)동희 02-6261-3782,"◆ 본 건물은 합정역(2호선, 6호선) 도보 5분 역세권 거리에 위치해 있어 대중교...",NaN
4,장고키친,서울 성동구 성수동1가 668-140,NaN,A,카카오,랜드북,나라,뚝섬역(2호선) 서울숲역(분당선),"700,000",NaN,...,강원애 481108-2 김지연 740812-2,김지연: 010-8866-5760,NaN,NaN,NaN,NaN,"서울특별시 서초구 동광로27길 88, 701호(반포동, 끄레메빌)\n\n밸83.3억...",* 2017.6 34.9억 매매 \n지구단위계획구역(뚝섬주변지역)\n*실거래 : 성...,본 건물은 뚝섬역(2호선) 도보4분 거리에 위치한 건물로 접근성이 우수함. 성수동 ...,NaN

In [18]:
df3[select_feature].head()

,기본,주소,상세주소,A,카맵,land,나라,주변역,입금가(만원),기타매매가(만원),...,고객,핸드폰,이메일,회사전화,자택전화,방향,메모,기타메모,건물특징,기타특징
0,상암바라라,서울 마포구 상암동 1452,NaN,A,카카오,랜드북,나라,"디지털미디어시티역(6호선, 공항선, 경의중앙선)","450,000",NaN,...,김진성 701025-1 유연아 780311-2,유연아 010-8714-2448,NaN,NaN,NaN,NaN,"경기도 고양시 일산동구 일산로 206, 302동 102호 (마두동,백마마을)",NaN,"◈ 디지털미디어시티역(6호선, 경의중앙선, 공항선)에서 도보 2분 거리 초역세권 위...",NaN
1,공릉역신축부지16,서울 노원구 공릉동 441-24,NaN,A,카카오,랜드북,나라,공릉역(7호선),"130,000",NaN,...,"최광철 711223-1, 최성례 800107-2",최광철 010-3724-9440,NaN,NaN,NaN,NaN,"서울특별시 노원구 공릉로34길 86, 110동1304호(공릉동,태릉해링턴플레이스)",NaN,▶ 공릉역(7호선) 도보 약 5분 거리에 위치한 건물로 대중교통 접근성 뛰어남.\n...,NaN
2,녹사평역신축부지32,서울 용산구 이태원동 225-207,90,A,카카오,랜드북,나라,녹사평역(6호선),"290,000",NaN,...,황민숙 470307-2,사위 전준형 010-9615-2804,NaN,NaN,NaN,NaN,서울 용산구 이태원동 260-60,황민숙님 돌아가심\n\n이태원동 225-207 76\n이태원동 225 - 90 30,◆ 녹사평역(6호선)도보 7분 거리 역세권에 위치한 건물로 대중교통 접근성이 뛰어남...,NaN
3,희원빌딩,서울 종로구 경운동 1-9,8,A,카카오,랜드북,나라,안국역(3호선),"490,000",NaN,...,윤인숙 680315-2,윤인숙 010-3736-9481,NaN,윤인숙 직통 02-6338-9481,NaN,NaN,서울특별시 종로구 삼일대로32길 22-4 (경운동),NaN,★ 안국역(3호선) 도보 3분 거리 초역세권에 위치한 건물로 대중교통 접근성이 뛰어...,NaN
4,대도빌딩,서울 중구 주자동 44-2,NaN,A,카카오,랜드북,나라,"충무로역(3호선, 4호선)","650,000",NaN,...,김정수 370215-2,김정수 010-3741-2237,NaN,"010-5228-4142, 02-2267-8609",NaN,NaN,성동구 구의동 233-21,NaN,"▶ 충무로역(3호선, 4호선) 도보 3분 거리 대로변 코너에 위치한 건물로 대중교통...",NaN

In [19]:
df4[select_feature].head()

,기본,주소,상세주소,A,카맵,land,나라,주변역,입금가(만원),기타매매가(만원),...,고객,핸드폰,이메일,회사전화,자택전화,방향,메모,기타메모,건물특징,기타특징
0,NaN,서울 은평구 신사동 19-153,NaN,A,카카오,랜드북,나라,NaN,0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,그랜드필드,서울 중구 남산동1가 16-6,NaN,A,카카오,랜드북,나라,NaN,0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,라루체웨딩홀,서울 중구 남산동1가 13-6,NaN,A,카카오,랜드북,나라,NaN,0,NaN,...,주식회사투데이아트,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,123호스텔,서울 중구 남산동2가 36-6,NaN,A,카카오,랜드북,나라,NaN,0,NaN,...,성광제620622-1,NaN,NaN,NaN,NaN,NaN,성광제 : 강남구 신사동 청록빌라,NaN,NaN,NaN
4,오요명동5롯지,서울 중구 남산동2가 33-3,NaN,A,카카오,랜드북,나라,NaN,0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
print(select_feature)


Building_ID : index 


['기본', '주소', '상세주소', 'A', '카맵', 'land', '나라', '주변역', '입금가(만원)', 
'기타매매가(만원)', '매매가(만원)', '수익률', '보증금(만원)', '평단가(만원)', '월 임대료(만원)', 
'관리비지출(만원)', '관리비(만원)', '관리비기타(만원)', '대출현황', '지목', '용도지역', '토지면적평', 
'토지면적미터', '미터당 공시지가(원)', '평당 공시지가(만원)', '공시합계(만원)', '도로', '사용승인일', 
'냉난방', '연면적평', '연면적미터', '지하층', '지상층', '승강기', '건폐율', '용적률', '주차방식', '주차대수', 
'고객', '핸드폰', '이메일', '회사전화', '자택전화', '방향', 


memo : '메모', '기타메모', '건물특징', '기타특징']

['기본', '주소', '상세주소', 'A', '카맵', 'land', '나라', '주변역', '입금가(만원)', '기타매매가(만원)', '매매가(만원)', '수익률', '보증금(만원)', '평단가(만원)', '월 임대료(만원)', '관리비지출(만원)', '관리비(만원)', '관리비기타(만원)', '대출현황', '지목', '용도지역', '토지면적평', '토지면적미터', '미터당 공시지가(원)', '평당 공시지가(만원)', '공시합계(만원)', '도로', '사용승인일', '냉난방', '연면적평', '연면적미터', '지하층', '지상층', '승강기', '건폐율', '용적률', '주차방식', '주차대수', '고객', '핸드폰', '이메일', '회사전화', '자택전화', '방향', '메모', '기타메모', '건물특징', '기타특징']

Building_ID
1. BD_number : int ( PK )
2. register_id_number : int
3. create_time : Datetime
4. update_time : Datetime
5. delete_flag : Boolean


Building_info 
1. BD_number : int ( pk )
2. BD_name : str(255) - 건물명
3. address : str(255) - 주소 
4. address_detail : str(255) - 상세주소
4. nearby_station : str(255) - 주변역 
5. deposit_price : int - 입금가 
6. other_sale_price: int - 기타매매가 
7. sale_price : int - 매매가 
8. yield_rate - int 수익률
9. security_deposit - int 보증금 
10. price_per_pyeong - int 평단가 
11. monthly_rent_fee - int 월 임대료  
12. maintenance_expense - int 관리비지출  
13. maintenance_fee - int 관리비 
14. maintenance_other_fee - int 관리비기타
15. loan_status - boolean 대출현황
16. land_category - str(255) 지목 
17. zoning_type - str(255) 용도지역
18. land_area_pyeong - int 토지면적평 
19. land_area_sqm - int 토지면적미터
20. official_price_per_sqm_won - int 미터당 공시지가
21. official_price_per_pyeong_million - int 평당 공시지가
22. official_price_total_million - int 공시합계
23. road_access - str(255) 도로
24. approval_date - datetime 사용승인일
25. heating_cooling - str(255) 냉난방 
26. gross_area_pyeong - int 연면적평
27. gross_area_sqm - int 연면적미터
28. underground_floors - int 지하층
29. aboveground_floors - int 지상층
30. elevator - int 승강기
31. building_coverage_ratio - int 건폐율
32. floor_area_ratio - int 용적률
33. parking_type - str(255) 주차방식
34. parking_capacity - int 주차대수
35. client_name - str(255) 고객명 
36. mobile_phone - str(255) 핸드폰
37. email - str(255) 이메일
38. office_phone - str(255) 회사전화
39. home_phone - str(255) 자택전화
40. orientation - str(255) 방향 



Building_memo
1. BD_number : int(pk)
2. loan_status : text
2. memo: text
3. etc_memo: text
4. BD_featrue: text
5. etc_featrue: text
3. create_time : Datetime
4. update_time : Datetime
5. delete_flag : Boolean